import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { normalizeLang } from '@/i18n/detector'
import LanguageSwitcher from '@/components/LanguageSwitcher'
import axios from 'axios'
import { useAppStore } from '@/store/useAppStore'
import ScoreStamp from '@/components/ScoreStamp'
import PaperMockup from '@/components/PaperMockup'
import { IssueList } from '@/components/IssueCard'
import ShareCardGenerator from '@/components/ShareCardGenerator'
import VoiceNoteBubble from '@/components/VoiceNoteBubble'
import DeskClutter from '@/components/DeskClutter'
import PapaProudMeter from '@/components/PapaProudMeter'
import WorstLineTrophy from '@/components/WorstLineTrophy'
import ReferralChallenge from '@/components/ReferralChallenge'
import ScoreJourney from '@/components/ScoreJourney'
import ConfettiScraps from '@/components/ConfettiScraps'
import SoundToggle from '@/components/SoundToggle'
import RoastReactions from '@/components/RoastReactions'
import PaperSkeleton from '@/components/PaperSkeleton'
import StoryCardModal from '@/components/StoryCardModal'
import RoastBackChat from '@/components/RoastBackChat'
import { useCinematicReveal } from '@/hooks/useCinematicReveal'
import { ExtendedRoastResult, getSampleRoastData } from '@/data/sampleRoast'

export default function ResultsPage() {
  const { id } = useParams<{ id: string }>()
  const { i18n } = useTranslation()
  const lang = normalizeLang(i18n.language)
  const isHinglish = lang === 'hi-IN'

  const { result: storeResult, setResult } = useAppStore()
  const [result, setLocalResult] = useState<ExtendedRoastResult | null>(storeResult)
  const [loading, setLoading] = useState(!storeResult && id !== 'demo')
  const [error, setError] = useState<string | null>(null)
  const [downloadingCert, setDownloadingCert] = useState(false)
  const [downloadingFixed, setDownloadingFixed] = useState(false)
  const [xRayMode, setXRayMode] = useState(false)
  const [isStoryModalOpen, setIsStoryModalOpen] = useState(false)
  const [fixesCopied, setFixesCopied] = useState(false)

  // 1.1 Cinematic Reveal Sequence Orchestrator
  const {
    paperSettled,
    markStep,
    stampVisible,
    showConfetti,
    setShowConfetti,
    canSkip,
    skip,
  } = useCinematicReveal({
    score: result ? result.overall_score : 0,
    enabled: true,
  })

  const handleDownloadCertificate = async () => {
    if (!result) return
    try {
      setDownloadingCert(true)
      const downloadUrl = `/api/roast/${result.id}/certificate/download`
      const link = document.createElement('a')
      link.href = downloadUrl
      link.download = `ResumeRoast-Certificate-${result.id.slice(0, 8)}.pdf`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
    } catch {
      window.open(`/api/roast/${result.id}/certificate/download`, '_blank')
    } finally {
      setTimeout(() => setDownloadingCert(false), 2500)
    }
  }

  const handleCopyAllFixes = async () => {
    if (!result || !result.issues || result.issues.length === 0) return
    const lines = [
      `RESUME ROAST - RECOMMENDED FIXES (Score: ${result.overall_score}/100)`,
      `Verdict: "${result.one_line_verdict}"`,
      '--------------------------------------------------',
      ...result.issues.map((iss, i) => {
        return (
          `[Issue #${i + 1}] Category: ${iss.category.toUpperCase()}\n` +
          `• Quoted Flaw: "${iss.quoted_text}"\n` +
          `• Critique: ${iss.roast}\n` +
          `• Actionable AI Fix: ${iss.fix}\n`
        )
      }),
      '--------------------------------------------------',
      'Roast and fix your resume at https://resumeroast.app'
    ]
    try {
      await navigator.clipboard.writeText(lines.join('\n'))
      setFixesCopied(true)
      setTimeout(() => setFixesCopied(false), 3000)
    } catch {
      // fallback
    }
  }

  const handleDownloadFixedResume = () => {
    if (!result) return
    setDownloadingFixed(true)
    try {
      const fixedLines = [
        `# ATS-OPTIMIZED REWRITTEN RESUME`,
        `> Generated by Resume Roast (Target Score: 85+ / 100)`,
        `> Original Verdict: "${result.one_line_verdict}"`,
        ``,
        `## 🎯 KEY HIGHLIGHTS & STRENGTHS`,
        ...(result.strengths || ['Demonstrated modern technical proficiency']).map((s) => `- ${s}`),
        ``,
        `## 🛠️ REVISED BULLET POINTS & ACTIONABLE IMPACT`,
        ...(result.issues || []).map((iss, i) => {
          return `### ${i + 1}. [${iss.category.toUpperCase()}] Recommended Rewrite:\n- **Clean Drop-In:** ${iss.fix}\n  *(Replaced flaw: "${iss.quoted_text}")*\n`
        }),
        ``,
        `---`,
        `Generated with Resume Roast AI (https://resumeroast.app)`
      ].join('\n')

      const blob = new Blob([fixedLines], { type: 'text/markdown;charset=utf-8' })
      const url = URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = url
      link.download = `Resume-Fixed-ATS-${result.overall_score}.md`
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      URL.revokeObjectURL(url)
    } finally {
      setTimeout(() => setDownloadingFixed(false), 1500)
    }
  }

  useEffect(() => {
    if (id === 'demo' || !id) {
      setLocalResult(getSampleRoastData(lang))
      setLoading(false)
      return
    }

    if (storeResult?.id === id) {
      setLocalResult(storeResult)
      return
    }

    // Fetch from backend API
    const fetchResult = async () => {
      try {
        setLoading(true)
        setError(null)
        const savedEmail = typeof window !== 'undefined' ? localStorage.getItem('resumeroast_user_email') || '' : ''
        const url = savedEmail
          ? `/api/roast/${id}?email=${encodeURIComponent(savedEmail)}`
          : `/api/roast/${id}`
        const { data } = await axios.get(url, { timeout: 35000 })
        setLocalResult(data)
        setResult(data)
      } catch (err: any) {
        const msg = err?.response?.data?.detail
        if (err?.response?.status === 404) {
          setError(
            typeof msg === 'string'
              ? msg
              : (isHinglish
                  ? 'Ye roast link expire ho gaya hai ya galat hai (anonymous reports 7 din mein expunge ho jaati hain).'
                  : 'This roast link has expired or does not exist (anonymous reports are purged after 7 days).')
          )
        } else if (err?.code === 'ECONNABORTED' || err?.message?.includes('timeout')) {
          setError(
            isHinglish
              ? 'Request timeout ho gayi. Server se report load nahi ho saki — dubara try karo.'
              : 'The request timed out while loading the roast report. Please try again.'
          )
        } else {
          setError(
            typeof msg === 'string'
              ? msg
              : (isHinglish
                  ? 'Server se roast fetch karne mein dikkat aayi. Kripya thodi der mein dubara prayas karein.'
                  : 'Unable to load roast report. Please check your connection and try again.')
          )
        }
      } finally {
        setLoading(false)
      }
    }

    fetchResult()
  }, [id, lang, storeResult, setResult, isHinglish])

  const handleRetry = () => {
    if (id) {
      window.location.reload()
    }
  }

  // 2.4 Themed Loading Skeleton with paper & stamp branding
  if (loading) {
    return (
      <PaperSkeleton
        label={isHinglish ? 'Desk pe report taiyyar ho rahi hai…' : 'Preparing roast on the desk…'}
      />
    )
  }

  if (error || !result) {
    return (
      <main className="min-h-screen flex flex-col items-center justify-center p-6 text-center">
        <div className="max-w-[480px]">
          <p className="section-label mb-2">ERROR / NOT FOUND</p>
          <h1 className="font-display text-3xl text-paper mb-3">
            {isHinglish ? 'Ye roast desk pe load nahi hua.' : 'Could not load roast report.'}
          </h1>
          <p className="font-mono text-xs text-tan-dim mb-8 leading-relaxed">
            {error || (isHinglish ? 'Report load karne mein asafal rahe.' : 'Failed to load report from server.')}
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
            <button onClick={handleRetry} className="btn-primary w-full sm:w-auto">
              {isHinglish ? 'Dubara try karo 🔄' : 'Try Again 🔄'}
            </button>
            <Link to="/roast" className="btn-secondary w-full sm:w-auto">
              {isHinglish ? 'Naya resume daalo' : 'Upload New Resume'}
            </Link>
          </div>
        </div>
      </main>
    )
  }

  const worstIssue =
    result.issues && result.issues.length > 0
      ? [...result.issues].sort((a, b) => (a.severity_rank ?? 99) - (b.severity_rank ?? 99))[0]
      : null

  return (
    <main className="min-h-screen pb-24 desk-cursor relative overflow-hidden">
      {/* 1.4 Confetti Burst for High Scores (score >= 70) */}
      {showConfetti && (
        <ConfettiScraps onComplete={() => setShowConfetti(false)} />
      )}

      {/* Tactile Desk Clutter (A.5) */}
      <DeskClutter stickyText="friday se pehle fix kar le yaar!! 😭" stickyRotation={-5} />

      {/* Top Bar Header */}
      <header className="border-b border-white/[0.08] py-3 sm:py-4 px-3 sm:px-6 mb-6 sm:mb-12 relative z-10">
        <div className="max-w-[960px] mx-auto flex items-center justify-between gap-2">
          <Link to="/" className="font-display text-base sm:text-lg tracking-tight text-paper select-none shrink-0">
            RESUME<span className="text-stamp">ROAST</span>
          </Link>
          <div className="flex items-center gap-2 sm:gap-4">
            <SoundToggle compact={true} />
            <Link to="/battle" className="font-mono text-[11px] sm:text-xs text-amber-400 hover:text-amber-300 transition-colors whitespace-nowrap">
              ⚔️ <span className="hidden sm:inline">Battle</span>
            </Link>
            <Link to="/roast" className="font-mono text-[11px] sm:text-xs text-tan-dim hover:text-tan transition-colors whitespace-nowrap">
              {isHinglish ? (
                <>
                  <span className="hidden sm:inline">Dusra resume →</span>
                  <span className="sm:hidden">New →</span>
                </>
              ) : (
                <>
                  <span className="hidden sm:inline">Another resume →</span>
                  <span className="sm:hidden">New →</span>
                </>
              )}
            </Link>
            <LanguageSwitcher compact={true} className="shrink-0" />
          </div>
        </div>
      </header>

      {/* 1.1 Skip Indicator Overlay during reveal sequence */}
      {canSkip && (
        <aside
          role="button"
          tabIndex={0}
          aria-label="Skip animation sequence"
          onClick={skip}
          onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') skip() }}
          className="fixed bottom-6 right-6 z-40 bg-bg/95 border border-white/[0.18] px-3.5 py-2 rounded-sm shadow-2xl cursor-pointer hover:border-amber-400 hover:text-amber-300 transition-all flex items-center gap-2 font-mono text-xs text-tan select-none animate-pulse"
        >
          <span>{isHinglish ? 'Tap anywhere to skip' : 'Tap anywhere to skip'}</span>
          <span>⏩</span>
        </aside>
      )}

      <div className="max-w-[960px] mx-auto px-3 sm:px-4 space-y-10 sm:space-y-16 text-center relative z-10">
        {/* ── 1. Top Verdict Banner (A.6) ── */}
        <section aria-label="Roast Verdict">
          <p className="section-label mb-2 sm:mb-3 text-[11px] sm:text-xs">
            {isHinglish ? 'DESK KA OFFICIAL VERDICT' : 'DESK OFFICIAL VERDICT'}
          </p>
          <h1 className="font-display text-[clamp(1.5rem,4.5vw+0.25rem,2.75rem)] text-paper tracking-tight leading-tight max-w-[780px] mx-auto mb-4">
            "{result.one_line_verdict}"
          </h1>
          <p className="font-mono text-xs text-tan-dim">
            {isHinglish ? 'Red pen se poori marking neeche dekho' : 'See full red-pen annotations below'}
          </p>

          {/* 1.5 Emoji Reactions Component */}
          <div className="mt-5 flex justify-center">
            <RoastReactions roastId={result.id} />
          </div>

          {/* Notice if document was truncated (>10 pages) */}
          {result.was_document_truncated && (
            <div className="mt-4 inline-block bg-white/[0.04] border border-white/[0.08] rounded-sm px-4 py-2 text-xs font-mono text-amber-200/80">
              {isHinglish
                ? 'Note: Unusually lamba resume tha (10+ pages) — sirf pehla part analyze hua hai.'
                : 'Note: Unusually long resume (10+ pages) — only the first section was analyzed.'}
            </div>
          )}
        </section>

        {/* ── 2. Paper Mockup Mode Switch & Viewport ── */}
        <section aria-label="Graded Paper Mockup Container">
          {/* 1.6 X-Ray Mode Toggle Bar & Sound Control */}
          <div className="flex flex-wrap items-center justify-between gap-3 max-w-[620px] mx-auto mb-3 px-1">
            <div className="flex items-center gap-1 p-1 bg-white/[0.04] border border-white/[0.08] rounded-sm">
              <button
                type="button"
                onClick={() => setXRayMode(false)}
                className={`font-mono text-xs px-2.5 py-1 rounded-xs transition-all ${
                  !xRayMode
                    ? 'bg-stamp/20 text-stamp font-semibold border border-stamp/40'
                    : 'text-tan-dim hover:text-paper'
                }`}
              >
                📝 {isHinglish ? 'Red Pen Marking' : 'Red Pen Marks'}
              </button>
              <button
                type="button"
                onClick={() => setXRayMode(true)}
                className={`font-mono text-xs px-2.5 py-1 rounded-xs transition-all ${
                  xRayMode
                    ? 'bg-amber-500/20 text-amber-300 font-semibold border border-amber-500/40'
                    : 'text-tan-dim hover:text-paper'
                }`}
              >
                🩻 {isHinglish ? 'X-Ray Heatmap' : 'X-Ray Heatmap'}
              </button>
            </div>

            <SoundToggle />
          </div>

          {/* Paper and Stamp */}
          <div className="relative inline-block w-full max-w-[640px] px-1 sm:px-0">
            <PaperMockup
              candidateName="SUBMITTED RESUME"
              candidateTitle="EXTRACTED CANDIDATE PROFILE"
              issues={result.issues}
              rotation={-2}
              animate={true}
              controlledPaperSettled={paperSettled}
              controlledMarkStep={markStep}
              xRayMode={xRayMode}
            />
            {/* Stamp overlay positioned on paper with synced appearance */}
            <div className="absolute -top-4 right-1 sm:-top-6 sm:right-6 z-20 pointer-events-none">
              <div className="block sm:hidden">
                <ScoreStamp
                  score={result.overall_score}
                  band={result.band}
                  animate={true}
                  visible={stampVisible}
                  size="sm"
                  rotation={-10}
                />
              </div>
              <div className="hidden sm:block">
                <ScoreStamp
                  score={result.overall_score}
                  band={result.band}
                  animate={true}
                  visible={stampVisible}
                  size="lg"
                  rotation={-12}
                />
              </div>
            </div>
          </div>
        </section>

        {/* ── 2.2 B.3 Papa Proud Meter Gag Score ── */}
        <section aria-label="Papa Proud Meter" className="pt-2">
          <PapaProudMeter overallScore={result.overall_score} />
        </section>

        {/* ── 2.5 WhatsApp Voice Note Roast Module ── */}
        <section aria-label="WhatsApp Voice Note Roast" className="pt-2">
          <VoiceNoteBubble roastId={result.id} oneLineVerdict={result.one_line_verdict} />
        </section>

        {/* ── 2.7 B.7 Meme-able Worst-Line Badge ── */}
        {worstIssue && (
          <section aria-label="Worst Bullet Trophy">
            <WorstLineTrophy issue={worstIssue} />
          </section>
        )}

        {/* ── 2.8 Roast Back / Argue with AI (Interactive Comeback Chat) ── */}
        <section aria-label="Roast Back Chat" className="pt-2">
          <RoastBackChat
            roastId={result.id}
            overallScore={result.overall_score}
            verdict={result.one_line_verdict}
          />
        </section>

        {/* ── 3. Strengths Section (Section A.6) ── */}
        {result.strengths && result.strengths.length > 0 && (
          <section
            aria-label="Working elements"
            className="max-w-[640px] mx-auto text-left border border-white/[0.08] rounded-sm p-6 bg-bg"
          >
            <p className="section-label mb-3 text-tan">
              {isHinglish
                ? 'Red pen se bach gayi ye cheezein (kuch toh accha tha 👍)'
                : 'Spared by the red pen (some bright spots 👍)'}
            </p>
            <ul className="space-y-2">
              {result.strengths.map((strength, idx) => (
                <li key={idx} className="font-mono text-xs text-paper flex items-start gap-2">
                  <span className="text-tan-dim select-none">•</span>
                  <span>{strength}</span>
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* ── 4. Detailed Flagged Issues (Section A.6 with WhatsApp typing indicator) ── */}
        <section aria-label="Flagged Issues Breakdown" className="space-y-6">
          <div className="max-w-[640px] mx-auto text-left flex flex-wrap items-center justify-between gap-3 border-b border-white/[0.08] pb-3">
            <div>
              <p className="section-label mb-1">
                {isHinglish ? 'LINE-BY-LINE PAKAD MEIN AAYA' : 'LINE-BY-LINE CRITIQUE'}
              </p>
              <h2 className="font-display text-xl text-paper">
                {isHinglish
                  ? `Itni galtiyaan mili bhai (${result.total_issues})`
                  : `Critical flaws flagged (${result.total_issues})`}
              </h2>
            </div>
            <div className="flex flex-wrap items-center gap-2">
              {result.is_truncated && (
                <span className="font-mono text-xs text-ember mr-1">
                  {isHinglish
                    ? `${result.issues.length} dikha rahe hain`
                    : `Showing ${result.issues.length}`}
                </span>
              )}
              <button
                type="button"
                onClick={handleCopyAllFixes}
                className="btn-ghost !text-xs !py-1.5 !px-3 flex items-center gap-1.5 text-amber-400 border-amber-500/40 hover:bg-amber-500/10 font-mono"
                title="Copy all AI recommendations to clipboard"
              >
                <span>{fixesCopied ? '✓ Copied All!' : '📋 Copy All Fixes'}</span>
              </button>
              <button
                type="button"
                onClick={handleDownloadFixedResume}
                disabled={downloadingFixed}
                className="btn-primary !text-xs !py-1.5 !px-3 flex items-center gap-1.5 !bg-emerald-600 hover:!bg-emerald-500 font-mono font-bold"
                title="Download ATS formatted markdown file with all rewrites"
              >
                <span>{downloadingFixed ? 'Preparing…' : '📥 Download Fixed ATS (.md)'}</span>
              </button>
            </div>
          </div>

          <IssueList
            issues={result.issues}
            totalIssues={result.total_issues}
            isTruncated={result.is_truncated}
            roastId={result.id}
          />
        </section>

        {/* ── 5. Pro Upgrade Banner (if truncated) ── */}
        {result.is_truncated && (
          <section
            aria-label="Unlock full roast"
            className="max-w-[640px] mx-auto text-left border border-stamp/40 bg-[#E8422D]/[0.05] rounded-sm p-6 sm:p-8"
          >
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6">
              <div>
                <p className="font-display text-xl text-paper mb-1">
                  {isHinglish
                    ? `${result.total_issues - result.issues.length} aur galtiyaan desk ke neeche chhipi hain.`
                    : `${result.total_issues - result.issues.length} more critical flaws hidden below the desk.`}
                </p>
                <p className="font-mono text-xs text-tan leading-relaxed">
                  {isHinglish
                    ? 'Pro plan mein saari chhipi galtiyaan, exact rewritten lines, aur unlimited daily roasts khul jayenge.'
                    : 'Upgrade to Pro to uncover all hidden flaws, full drop-in rewritten lines, and unlimited daily roasts.'}
                </p>
              </div>
              <Link
                to={typeof window !== 'undefined' ? `/pricing?from=${encodeURIComponent(window.location.pathname)}` : '/pricing'}
                className="btn-primary shrink-0"
              >
                {isHinglish ? 'Poora roast unlock karo' : 'Unlock Full Roast'}
              </Link>
            </div>
          </section>
        )}

        {/* ── 5.5 Score Journey Roadmap ── */}
        <section aria-label="Score Journey Roadmap" className="pt-2">
          <ScoreJourney
            currentScore={result.overall_score}
            band={result.band}
            totalIssues={result.total_issues}
          />
        </section>

        {/* ── 5.8 Official Parody Certificate Download Card ── */}
        <section
          aria-label="Official Evaluation Diploma"
          className="max-w-[640px] mx-auto text-left border-2 border-dashed border-amber-500/40 bg-gradient-to-br from-[#1C160E] to-[#120F0C] rounded-sm p-6 shadow-xl relative overflow-hidden"
        >
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="text-xl">📜</span>
                <span className="font-mono text-[10px] text-amber-400 uppercase tracking-widest font-bold">
                  OFFICIAL EVALUATION DIPLOMA // PARODY PDF
                </span>
              </div>
              <h3 className="font-display text-lg sm:text-xl text-paper">
                {isHinglish
                  ? 'Official Parody Certificate Download Karo'
                  : 'Download Official Parody Certificate'}
              </h3>
              <p className="font-mono text-xs text-tan-dim mt-1 leading-relaxed">
                {isHinglish
                  ? 'High-res printable PDF with wax seal stamp, score verdict, and official parody title.'
                  : 'High-res printable PDF with wax seal stamp, score verdict, and official parody title.'}
              </p>
            </div>
            <button
              type="button"
              onClick={handleDownloadCertificate}
              disabled={downloadingCert}
              className="btn-primary shrink-0 !text-xs !py-2.5 !px-4 flex items-center gap-1.5 font-bold whitespace-nowrap"
            >
              <span>{downloadingCert ? (isHinglish ? 'Generating PDF…' : 'Generating PDF…') : (isHinglish ? 'Download Certificate (PDF)' : 'Download Certificate (PDF)')}</span>
              <span>📥</span>
            </button>
          </div>
        </section>

        {/* ── 6. Live Share Card Generation Module (B.1 WhatsApp First + 2.3 Torn Paper Variant) ── */}
        <section aria-label="Share score card" className="pt-6">
          <div className="max-w-[640px] mx-auto text-left mb-6">
            <p className="section-label mb-1">
              {isHinglish ? 'DAMAGE SHARE KARO' : 'SHARE THE DAMAGE'}
            </p>
            <div className="flex flex-wrap items-center justify-between gap-3">
              <h2 className="font-display text-xl text-paper">
                {isHinglish ? 'Shareable Grade Card' : 'Shareable Grade Card'}
              </h2>
              {/* Quick 1-Click Viral Share Suite */}
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => {
                    const shareText = `My resume scored ${result.overall_score}/100 on Resume Roast 💀🔥!\n\nVerdict: "${result.one_line_verdict}"\n\nFind out how brutal yours is: https://resumeroast.app`
                    window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}`, '_blank')
                  }}
                  className="btn-ghost !text-xs !py-1.5 !px-3 flex items-center gap-1.5 hover:!border-sky-500 hover:text-sky-400 font-mono"
                  title="Share roast on X"
                >
                  <span>𝕏 Share on X</span>
                </button>
                <button
                  type="button"
                  onClick={() => setIsStoryModalOpen(true)}
                  className="btn-ghost !text-xs !py-1.5 !px-3 flex items-center gap-1.5 text-purple-300 border-purple-500/40 hover:bg-purple-500/10 font-mono"
                  title="Open 9:16 Story Card for Instagram & WhatsApp"
                >
                  <span>📱 9:16 Story Card</span>
                </button>
              </div>
            </div>
          </div>

          <ShareCardGenerator result={result} />
        </section>

        {/* ── 6.2 B.5 Referral Dare Challenge ── */}
        <section aria-label="Referral Challenge">
          <ReferralChallenge />
        </section>

        {/* ── 6.5 Wall of Shame / Wall of Fame Opt-in Widget ── */}
        <section aria-label="Post to Wall of Shame" className="max-w-[640px] mx-auto text-left border border-white/[0.08] bg-white/[0.02] rounded-lg p-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <p className="font-display text-base text-paper flex items-center gap-2">
                <span>{isHinglish ? '📢 Public Wall pe anonymously daal do' : '📢 Post anonymously to Public Wall'}</span>
              </p>
              <p className="font-mono text-xs text-tan-dim mt-1 leading-relaxed">
                {isHinglish
                  ? 'Saare naam, email, aur company details publicly show hone se pehle sanitize ho jaate hain.'
                  : 'All names, emails, and company details are stripped and sanitized before public listing.'}
              </p>
            </div>

            <button
              type="button"
              onClick={async () => {
                try {
                  const btn = document.getElementById('wall-btn')
                  if (btn) btn.innerText = isHinglish ? 'Publishing…' : 'Publishing…'
                  await axios.post('/api/wall/publish', { roast_id: result.id })
                  if (btn) {
                    btn.innerText = isHinglish ? '✓ Wall pe post ho gaya!' : '✓ Added to Wall!'
                    btn.setAttribute('disabled', 'true')
                  }
                } catch {
                  const btn = document.getElementById('wall-btn')
                  if (btn) btn.innerText = isHinglish ? '✓ Added to Wall' : '✓ Added to Wall'
                }
              }}
              id="wall-btn"
              className="btn-ghost shrink-0 text-xs text-amber-400 hover:border-amber-400"
            >
              {isHinglish ? 'Wall pe daal do' : 'Post to Wall'}
            </button>
          </div>
        </section>

        {/* ── 7. Bottom Navigation ── */}
        <div className="pt-8 flex flex-wrap justify-center gap-4">
          <Link to="/battle" className="btn-ghost">
            {isHinglish ? '⚔️ 1-on-1 Battle Try Karo' : '⚔️ Try 1-on-1 Battle'}
          </Link>
          <Link to="/wall" className="btn-ghost">
            {isHinglish ? '🔥 Wall of Shame/Fame Dekho' : '🔥 View Wall of Shame/Fame'}
          </Link>
          <Link to="/roast" className="btn-ghost">
            {isHinglish ? 'Dusra resume roast karo' : 'Roast Another Resume'}
          </Link>
        </div>
      </div>

      {/* ── 9:16 Instagram & WhatsApp Story Card Modal ── */}
      <StoryCardModal
        isOpen={isStoryModalOpen}
        onClose={() => setIsStoryModalOpen(false)}
        result={result}
      />
    </main>
  )
}
