import { Link } from "react-router-dom";
import { usePageTitle } from "@/utils/usePageTitle";

export default function TermsPage() {
  usePageTitle("Terms of Service");
  return (
    <main className="min-h-screen pb-24">
      {/* Top Bar Header */}
      <header className="border-b border-white/[0.08] py-4 px-6 mb-12">
        <div className="max-w-[960px] mx-auto flex items-center justify-between">
          <Link
            to="/"
            className="font-display text-lg tracking-tight text-paper select-none"
          >
            RESUME<span className="text-stamp">ROAST</span>
          </Link>
          <Link
            to="/"
            className="font-mono text-xs text-tan-dim hover:text-tan transition-colors"
          >
            ← Back to Desk
          </Link>
        </div>
      </header>

      <div className="max-w-[720px] mx-auto px-4 text-left space-y-8">
        <div>
          <p className="section-label mb-2">LEGAL &amp; COMPLIANCE</p>
          <h1 className="font-display text-3xl sm:text-4xl text-paper tracking-tight mb-3">
            Terms of Service
          </h1>
          <p className="font-mono text-xs text-tan-dim">
            Last updated:{" "}
            {new Date().toLocaleDateString("en-US", {
              month: "long",
              year: "numeric",
            })}
          </p>
        </div>

        <div className="space-y-6 font-body text-sm text-tan leading-relaxed">
          <section className="border-t border-white/[0.08] pt-6">
            <h2 className="font-display text-lg text-paper mb-2">
              1. Nature of the Service &amp; AI Disclaimer
            </h2>
            <p>
              Resume Roast provides automated, opinionated, AI-generated resume
              critiques, scoring, and suggested bullet point rewrites. Feedback
              is intended strictly for entertainment, educational, and general
              career guidance purposes.
            </p>
            <p className="mt-2 font-mono text-xs text-tan-dim">
              The feedback is generated by artificial intelligence and does NOT
              constitute licensed human career counseling, recruitment agency
              advice, or an endorsement of your hiring prospects. We make zero
              guarantees regarding interview invitations, job offers, ATS
              compliance pass rates, or salary outcomes.
            </p>
          </section>

          <section className="border-t border-white/[0.08] pt-6">
            <h2 className="font-display text-lg text-paper mb-2">
              2. User Responsibility &amp; No Liability
            </h2>
            <p>
              You retain sole and absolute responsibility for your job
              applications, career materials, and the accuracy of any resume you
              choose to submit to employers. You must review and verify all AI
              rewrite suggestions before incorporating them into your official
              documents. Resume Roast accepts no liability for employment
              decisions, rejections, or missed opportunities.
            </p>
          </section>

          <section className="border-t border-white/[0.08] pt-6">
            <h2 className="font-display text-lg text-paper mb-2">
              3. Acceptable Use Policy
            </h2>
            <p>
              You agree to upload only genuine resume or curriculum vitae
              documents that you own or have explicit legal authorization to
              submit. You must NOT:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1 text-xs font-mono text-tan-dim">
              <li>
                Upload files containing malicious code, viruses, or corrupted
                binaries.
              </li>
              <li>
                Submit documents containing third-party confidential trade
                secrets or unauthorized personal data.
              </li>
              <li>
                Attempt scripted abuse, DDoS attacks, or automated scraping
                designed to exhaust server or AI API resources.
              </li>
              <li>
                Upload content that is unlawful, defamatory, harassing, or
                sexually explicit.
              </li>
            </ul>
            <p className="mt-2 text-xs text-tan-dim">
              We reserve the right to immediately rate-limit, block, or
              permanently ban any IP address or user account violating this
              policy.
            </p>
          </section>

          <section
            className="border-t border-white/[0.08] pt-6"
            id="refund-policy"
          >
            <h2 className="font-display text-lg text-paper mb-2">
              4. 7-Day Refund Policy
            </h2>
            <p>
              We want you to be completely satisfied with your Resume Roast
              experience:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1.5 text-xs font-mono text-tan-dim">
              <li>
                <strong className="text-paper">Technical Faults:</strong> If you
                paid for a Single Roast pass (₹99) or Pro subscription (₹799)
                and a verified system outage or bug prevented your report from
                generating, you are entitled to a 100% full refund.
              </li>
              <li>
                <strong className="text-paper">Satisfaction Guarantee:</strong>{" "}
                If you request a refund within 7 days of purchase and have
                completed fewer than two (2) paid roasts under that billing
                period, we will issue a full refund without questions.
              </li>
              <li>
                <strong className="text-paper">How to Request:</strong> Email{" "}
                <a
                  href="mailto:support@resumeroast.app"
                  className="text-amber-400 underline"
                >
                  support@resumeroast.app
                </a>{" "}
                with your payment ID or order receipt from Razorpay. Refunds are
                processed back to your original payment method (UPI / Bank /
                Card) within 3–5 business days.
              </li>
            </ul>
          </section>

          <section className="border-t border-white/[0.08] pt-6">
            <h2 className="font-display text-lg text-paper mb-2">
              5. Pro Billing &amp; Subscriptions
            </h2>
            <p>
              Paid passes and subscriptions are billed in advance via authorized
              India-first payment gateways (Razorpay supporting UPI, RuPay,
              Netbanking, and Cards). Recurring plans can be cancelled at any
              time; cancellation takes effect at the end of the current billing
              cycle with no surprise auto-renewals.
            </p>
          </section>

          <section className="border-t border-white/[0.08] pt-6">
            <h2 className="font-display text-lg text-paper mb-2">
              6. Limitation of Liability
            </h2>
            <p>
              To the fullest extent permitted by applicable law, Resume Roast
              and its operators shall not be liable for any direct, indirect,
              incidental, punitive, or consequential damages arising out of your
              use of or inability to use this platform.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
